### ISSUE TITLE
Missing image edit in README

### ISSUE THREAD

**Issue by cchoirat** [EricaMoreira/SemSeg#5]
> Open 3D Slicer, and display the Python Interactor by clicking the button circled at the top right

Button is not circled:

![image](https://user-images.githubusercontent.com/4173925/64459550-6ff05900-d0f8-11e9-84f2-91b0dc164723.png)

**Comment by EricaMoreira** [comment]
Took out the word "circled". The button is at the top right and has a tooltip when you hover over it, so there shouldn't be any confusion.
